sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.0

notifications:
  email: false

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.6.1
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.6.0
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
